<!doctype html>
<html>
<head>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/tify@0.34.4/dist/tify.css">
    <style type="text/css">
    <?php echo $tifyConfig['tifyContainerStyles']; ?>
    </style>
</head>
<body>
    <?php $a = 0; ?>
    <div id="tify"></div>
    <script type="module">
        import 'https://cdn.jsdelivr.net/npm/tify@0.34.4/dist/tify.js'
        const tify = new Tify({
            container: '#tify',
            manifestUrl: "<?php echo $tifyConfig['manifestUrl']; ?>",
            pageLabelFormat: 'P',
            urlQueryKey: 'tify',
        })
    </script>
</body>
</html>
